This Testing, Error after run.py Contact : @stelaer in Telegram

Install : ```git clone https://github.com/Megaxuze/tbot.git```
Folder : ```cd tbot```
Install : ```apt install python3```
Requitment : ```pip install -r requirements.txt```
Change Private key in PrivateKeys.py

Run :```Python3 run.py```
